apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"2"},"creationTimestamp":"2025-10-14T11:37:38Z","generation":3,"labels":{"app":"synergychat-api"},"name":"synergychat-api","namespace":"default","resourceVersion":"52082","uid":"93c31bff-8348-41d6-b7c6-24a5cf4e338a"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"synergychat-api"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"synergychat-api"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"synergychat-api-configmap"}}],"image":"bootdotdev/synergychat-api:latest","imagePullPolicy":"Always","name":"synergychat-api","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2025-10-14T12:35:35Z","lastUpdateTime":"2025-10-14T12:36:48Z","message":"ReplicaSet \"synergychat-api-865f7fd885\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2025-10-15T11:02:42Z","lastUpdateTime":"2025-10-15T11:02:42Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":3,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2025-10-14T11:37:38Z"
  generation: 4
  labels:
    app: synergychat-api
  name: synergychat-api
  namespace: default
  resourceVersion: "82842"
  uid: 93c31bff-8348-41d6-b7c6-24a5cf4e338a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: synergychat-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: synergychat-api
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: synergychat-api-configmap
        image: bootdotdev/synergychat-api:latest
        imagePullPolicy: Always
        name: synergychat-api
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - name: synergychat-api-volume
            mountPath: /persist
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: synergychat-api-volume
          persistentVolumeClaim:
            claimName: synergychat-api-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-10-14T12:35:35Z"
    lastUpdateTime: "2025-10-15T11:06:41Z"
    message: ReplicaSet "synergychat-api-6798b468f6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-10-18T07:57:27Z"
    lastUpdateTime: "2025-10-18T07:57:27Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
