apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: synergychat-api
  ports:
    - protocol: TCP #(TCP will allow us to use HTTP)
      nodePort: 30080
      port: 80 #(this is the port that the service will listen on)
      targetPort: 8080 #(this is the port that the pods are listening on)
