apiVersion: v1
kind: Service
metadata:
  name: crawler-service
  namespace: crawler
spec:
  selector:
    app: synergychat-crawler
  ports:
    - protocol: TCP #(TCP will allow us to use HTTP)
      port: 80 #(this is the port that the service will listen on)
      targetPort: 8080 #(this is the port that the pods are listening on)
