apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"synergychat-testcpu"},"name":"synergychat-testcpu","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"synergychat-testcpu"}},"template":{"metadata":{"labels":{"app":"synergychat-testcpu"}},"spec":{"containers":[{"image":"bootdotdev/synergychat-testcpu:latest","name":"synergychat-testcpu","resources":{"limits":{"cpu":"50m"}}}]}}}}
  creationTimestamp: "2025-10-19T11:54:21Z"
  generation: 1
  labels:
    app: synergychat-testcpu
  name: synergychat-testcpu
  namespace: default
  resourceVersion: "157516"
  uid: 7f61e794-92e6-46b2-81c8-8371d896f2a7
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: synergychat-testcpu
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: synergychat-testcpu
    spec:
      containers:
      - image: bootdotdev/synergychat-testcpu:latest
        imagePullPolicy: Always
        name: synergychat-testcpu
        resources:
          limits:
            cpu: 50m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-10-19T11:54:21Z"
    lastUpdateTime: "2025-10-19T11:54:46Z"
    message: ReplicaSet "synergychat-testcpu-56895ff97f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-10-19T14:47:16Z"
    lastUpdateTime: "2025-10-19T14:47:16Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
